POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "natan",
  "password": "natan2"
}

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "natan",
  "password": "natan2"
}


###

GET http://localhost:8080/auth/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmF0YW4iLCJpYXQiOjE2MjQwMjc3NjF9.TZc7uQoAo58z95yaC_Bze6s9e3WhasPmlwLNJ2Mjp64


###

POST https://engsoft-production-nmcardoso.cloud.okteto.net/auth/login
Content-Type: application/json

{
  "username": "natan",
  "password": "natan2"
}


###

POST https://engsoft-production-nmcardoso.cloud.okteto.net/auth/register
Content-Type: application/json

{
  "username": "natan",
  "password": "natan2"
}