POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "natan",
  "password": "natan2"
}

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "natan",
  "password": "natan2"
}


###


GET http://localhost:8080/auth/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmF0YW4iLCJpYXQiOjE2MjQ1Mjg5MzN9.1kQoxXuKN0ZOCXCw05GIkLxkuWV5LXJ7GaDQivXAZSg


###

GET http://localhost:8080/auth/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmF0YW4iLCJpYXQiOjE2MjQwMjc3NjF9.TZc7uQoAo58z95yaC_Bze6s9e3WhasPmlwLNJ2Mjp64


###


POST http://localhost:8080/formulario/
Content-Type: application/json

{
  "id_unidade_saude": 1,
  "cpf": "112233445566",
  "telefone": "66778899",
  "nome": "Natanael",
  "data_nascimento": "2000-02-17",
  "laboratorio": "Astra",
  "lote": 11,
  "data_vacinacao": "2021-04-04 00:00:00",
  "dose": 2
}


###


GET http://localhost:8080/unidade_saude/?campos=nome,id


###



POST https://engsoft-production-nmcardoso.cloud.okteto.net/auth/login
Content-Type: application/json

{
  "username": "natan",
  "password": "natan2"
}


###

POST https://engsoft-production-nmcardoso.cloud.okteto.net/auth/register
Content-Type: application/json

{
  "username": "natan",
  "password": "natan2"
}
