name: server_deploy
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '/chart/**'
      - 'okteto-pipeline.yml'
      - '.github/workflows/api_deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: Deploy application
      uses: okteto/pipeline@master
      with:
        name: engsoft-production
        namespace: nmcardoso