name: client_deploy
on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Packages
        run: |
          cd client
          npm ci
      - name: Build & Deploy to GH Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git remote set-url origin https://nmcardoso:${{ secrets.GITHUB_TOKEN }}@github.com/nmcardoso/engsoft.git
          cd client
          npm run deploy
        env:
          PUBLIC_URL: https://nmcardoso.github.io/engsoft
