name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Packages
        run: |
          cd client
          npm install
      - name: Build & Deploy to GH Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/nmcardoso/engsoft.git
          cd client
          npm run deploy

  deploy_server:
    runs-on: ubuntu-latest
    steps:
      - name: request
        run: |
          curl -H "deploy_key: ${{ secrets.deploy_key }}" -X GET https://engsoft.glitch.me/deploy